name: build

on:
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize, reopened]
  workflow_run:
    workflows: ["linter"]
    types:
      - completed

jobs:
  build:
    name: docker compose
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v3

      - name: Docker Compose
        run: docker compose -f docker-compose.yml up -d --build

      - name: Wait for docker to finish building
        run: sleep 30

      - name: Docker PS
        run: docker compose ps

      - name: Cargo Check Apollo
        run: docker exec apollo cargo --version