name: build

on:
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize, reopened]
  workflow_run:
    workflows: ["linter"]
    types:
      - completed

jobs:
  build:
    name: docker compose
    runs-on: ubuntu-latest
    steps:

      - name: check out
        uses: actions/checkout@v3

      - name: docker compose
        run: docker compose -f docker-compose.yml up -d --build

      - name: "Wait for docker to finish building"
        run: sleep 10

      - name: Cargo Check
        run: docker exec athena cargo check

      - name: Cargo Check
        run: docker exec apollo cargo check